### ISSUE TITLE
getting 3d model viewer into the app store

### ISSUE THREAD

**Issue by koebel** [saw-jan/web-app-3dmodel-viewer#20]
### Description

check if all these points mentioned by Benedikt are covered before the next release: https://github.com/owncloud/web/issues/11330

- [x] manifest.json 
- [x] publicly available .zip file 
- [x] cover image
- [x] minimal QA on the app
- [x] add all information incl. screenshots to https://github.com/owncloud/awesome-ocis/blob/main/webApps/apps.json 

I think the first two points are already done for this app :)

### User Stories

As a creator of ocis web extensions
I want to my extension to be listed in the marketplace
So that users can find and install it easily

### Acceptance Criteria

all points above are implemented

**Comment by koebel** [comment]
I just noticed that there is already another 3D viewer in the marketplace, however Benedict really wants your app to be included in awesome-ocis :)

Maybe have a look at it and make sure to emphasize in communication the things that your extension does better

Here is the other app: https://marketplace.owncloud.com/apps/files_3dviewer

**Comment by saw-jan** [comment]
>Here is the other app: https://marketplace.owncloud.com/apps/files_3dviewer

this should be the apps for oc10 server

**Comment by saw-jan** [comment]
But yeah,  I will soon trim it for the ocis web-extension
