### ISSUE TITLE
[feature] changing UI to dark mode

### ISSUE THREAD

**Issue by koebel** [saw-jan/web-app-3dmodel-viewer#3]
It would also be nice to enable changing the UI to dark mode. For some object the visibility might be better on dark background and also depending on lighting situation, it might be more convenient to have dark background.

## User Story
As a user
I want to change the UI to dark mode
so that I can see my object better

## Acceptance Criteria
- changing of UI to dark mode should not only affect the ocis web UI elements but also the background colour and control elements of this extension

**Comment by saw-jan** [comment]
>changing of UI to dark mode should not only affect the ocis web UI elements but also the background colour and control elements of this extension

I believe this has been implemented already.

**Comment by koebel** [comment]
nice
