### ISSUE TITLE
enable installation through yml file

### ISSUE THREAD

**Issue by koebel** [saw-jan/web-app-3dmodel-viewer#32]
For next oCIS release it is desired to enable installation of web extensions through yml file

## User Story
Aa a system admin
I want to add 3D Model Viewer as easily as possible to my environment
so that I have as little work as possible

## Acceptance Criteria
- create yml file to enable admins to add 3D Model Viewer with only a few lines in .env to the oCIS deployment example similar to https://github.com/owncloud/ocis/tree/master/deployments/examples/ocis_full/web_extensions
- add short description of what needs to be done by admin in README (copy yml file to "web_extensions" folder, add variable with path to the .env file, and append the variable to COMPOSE_FILE at the very end of the .env file)

**Comment by saw-jan** [comment]
Things required before this:
- docker image

**Comment by saw-jan** [comment]
docker image is available: https://hub.docker.com/r/sawjan/3dviewer/tags
updated the docs in PR #33
